stages:
  01_data_ingestion:
    cmd: python src/components/module_01_data_ingestion.py
    deps:
      - src/components/module_01_data_ingestion.py
      - src/constants/data_ingestion_constants.py
      - src/entity/data_ingestion_artifact.py
    outs:
      - artifact/raw
    
  02_data_validation:
    cmd: python src/components/module_02_data_validation.py
    deps:
      - src/components/module_02_data_validation.py
      - artifact/raw
      - config/schema.yaml
      - src/constants/data_validaton_constant.py
      - src/entity/data_validation_artifact.py
      - src/entity/data_ingestion_artifact.py
      - src/constants/data_ingestion_constants.py
    outs:
      - validation_report/validation_report.yaml
  
  03_data_transformation:
    cmd: python src/components/module_03_data_transformation.py
    deps:
      - src/components/module_03_data_transformation.py
      - validation_report/validation_report.yaml
      - src/constants/data_transformation_constant.py
      - src/entity/data_transformation_artifact.py
      - artifact/raw
    outs:
      - artifact/interim
  
  04_feature_quality_filter:
    cmd: python src/components/module_04_feature_quality_filter.py
    deps:
      - src/components/module_03_data_transformation.py
      - src/components/module_04_feature_quality_filter.py.py
      - artifact/interim
      - src/constants/data_quality_check_constant.py
      - src/entity/quality_check_artifact.py
      - artifact/interim/main_df_transformed.csv
    #outs:
      #- artifact/data_quality/main_df_feature_quality_df.csv

  05_woe_binning_and_selection:
    cmd: python src/components/module_05_woe_binning_and_selection.py
    deps:
      - src/components/module_05_woe_binning_and_selection.py
      - src/components/module_04_feature_quality_filter.py
      - src/entity/data_transformation_artifact.py
      - src/constants/feature_engineering_constant.py
      - artifact/interim/main_df_transformed.csv
    outs:
      - artifact/splits/X_train.csv
      - artifact/splits/X_test.csv
      - artifact/splits/y_train.csv
      - artifact/splits/y_test.csv
      - artifact/binning/prebin/iv_df.csv
      - artifact/binning/prebin/cat_bin_df.csv
      - artifact/binning/prebin/numerical_feature_bins.pkl
      - artifact/binning/prebin/selected_features.json

  06_bin_refinement_and_selection:
    cmd: python src/components/module_06_bin_refinement_and_selection.py

    deps:
      - src/components/module_06_bin_refinement_and_selection.py
      - artifact/binning/prebin/X_train_selected_woe.csv 
      - artifact/binning/prebin/X_test_selected_woe.csv 
      - artifact/binning/prebin/iv_df.csv
      - src/entity/manual_bin_merging_artifact.py              
      - src/constants/manual_bin_merging.py    
      - artifact/binning/post_bin_manual/selected_features.json  # manualy selected features
    outs:
      - artifact/final/X_train_final.csv
      - artifact/final/X_test_final.csv
      
  07_model_training:
    cmd: python src/components/module_07_model_training.py
    deps:
      - src/components/module_07_model_training.py
      - src/components/module_06_bin_refinement_and_selection.py
      - artifact/data/final/X_train_final.csv
      - artifact/data/data_splits/y_train.csv
    params:
      - params.yaml:
          - model_training
    outs:
      - artifact/model/model.pkl
      - artifact/model/feature_importance.csv

  08_model_evaluation:
    cmd: python src/components/module_08_model_evalution.py
    deps:
      - src/components/module_08_model_evalution.py
      - artifact/model/model.pkl
      - artifact/data/final/X_train_final.csv
      - artifact/data/final/X_test_final.csv
      - artifact/data/data_splits/y_train.csv
      - artifact/data/data_splits/y_test.csv
    outs:
      - artifact/model_eval/roc_curve.png
    metrics:
      - artifact/model_eval/metrics.json

  09_scorecard:
    cmd: python src/components/module_09_scorecard.py
    deps:
      - src/components/module_09_scorecard.py
      - artifact/model/model.pkl
      - artifact/model/feature_importance.csv
      - artifact/data/final/X_train_final.csv
      - artifact/data/final/selected_num_bins.pkl
      - artifact/binning/prebin/iv_df.csv
      - artifact/binning/prebin/cat_bin_df.csv
      - artifact/data/data_splits/y_train.csv
    outs:
      - artifact/scorecard/final_scorecard_rules.csv
      - artifact/scorecard/scorecard_numerical_rules.csv
      - artifact/scorecard/scorecard_categorical_rules.csv
      - artifact/scorecard/scorecard_numerical_lookup.pkl
      - artifact/scorecard/scorecard_categorical_lookup.pkl
      - artifact/scorecard/scorecard_scaling_params.json
      - artifact/scorecard/scored_train.csv
      - artifact/scorecard/scorecard_table.csv
    metrics:
      - artifact/scorecard/scorecard_metrics.json
