stages:
  01_data_ingestion:
    cmd: python src/components/01_data_ingestion.py
    deps:
      - src/components/01_data_ingestion.py
      - src/constants/data_ingestion_constants.py
      - src/entity/data_ingestion_artifact.py
    outs:
      - artifact/raw
  
  
 