[project]
name = "src"
version = "0.0.1"
description = "Home Credit Risk Loan Analysis"
authors = [{name = "Rajguru Bhosale", email = "bhosalerajguru007@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}