import os
from pathlib import Path

# GLOBAL DIR
# ALWAYS RESOLVE PROJECT ROOT
PROJECT_ROOT = Path(__file__).resolve().parents[2]
ARTIFACT_DIR = PROJECT_ROOT / "artifact"
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)


ARTIFACT_BINNING_DIR = ARTIFACT_DIR / 'binning'
ARTIFACT_BINNING_DIR.mkdir(parents=True, exist_ok=True)

ARTIFACT_MODEL_DIR = ARTIFACT_DIR / 'model'
ARTIFACT_MODEL_DIR.mkdir(parents=True, exist_ok=True)

ARTIFACT_MODEL_EVAL_DIR = ARTIFACT_DIR / 'model_eval'
ARTIFACT_MODEL_EVAL_DIR.mkdir(parents=True, exist_ok=True)

ARTIFACT_SCORECARD_DIR = ARTIFACT_DIR / 'scorecard'
ARTIFACT_SCORECARD_DIR.mkdir(parents=True, exist_ok=True)




PARAMS_DIR_PATH = Path("params.yaml")

ARTIFACT_VALIDATION_DIR_PATH = ARTIFACT_DIR / "validation"
ARTIFACT_VALIDATION_DIR_PATH.mkdir(parents=True,exist_ok=True)

ARTIFACT_DATA_DIR = ARTIFACT_DIR / "data"
ARTIFACT_DATA_DIR.mkdir(parents=True,exist_ok=True)

ARTIFACT_DATA_SPLITS_DIR = ARTIFACT_DATA_DIR / 'data_splits'
ARTIFACT_DATA_SPLITS_DIR.mkdir(parents=True,exist_ok=True)



#DATA INGESTION
SOURCE_RAW_DATA_URL = Path(r"D:\credit risk datasets\datas")

DATABASE_NAMES_LIST = [
    "application_data.csv",
    "bureau.csv",
    "bureau_balance.csv",
    "credit_card_balance.csv",
    "installments_payments.csv",
    "POS_CASH_balance.csv",
    "previous_application.csv"
]


#dir to save datasets
ARTIFACT_DATA_RAW_DIR = ARTIFACT_DATA_DIR / 'raw'
ARTIFACT_DATA_RAW_DIR.mkdir(parents=True,exist_ok= True)

APPLICATION_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "application_data.csv"
BUREAU_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "bureau.csv"
BUREAU_BALANCE_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "bureau_balance.csv"
CREDIT_CARD_BALANCE_PATH = ARTIFACT_DATA_RAW_DIR / "credit_card_balance.csv"
INSTALLMENT_PAYMENTS_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "installments_payments.csv"
POS_CASH_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "POS_CASH_balance.csv"
PREVIOUS_APPLICATION_DATA_PATH = ARTIFACT_DATA_RAW_DIR / "previous_application.csv"

#DATA VALIDATION
VALIDATION_REPORT_PATH = ARTIFACT_VALIDATION_DIR_PATH / 'validation_report.yaml'

# DATA TRANSFORMATION
ARTIFACT_DATA_INTERIM_DIR = ARTIFACT_DATA_DIR / 'interim'
ARTIFACT_DATA_INTERIM_DIR.mkdir(parents=True,exist_ok=True)

ARTIFACT_DATA_INTERIM_MAIN_DF_DIR = ARTIFACT_DATA_INTERIM_DIR / 'main_df_transformed.csv'


# FEATURE QUALITY FILTER 
VALIDATION_FEATURE_QUALITY_PATH = ARTIFACT_VALIDATION_DIR_PATH / 'main_df_feature_quality.csv'

# FEATURE ENGINEERING
DATA_SPLITS_X_TRAIN_PATH = ARTIFACT_DATA_SPLITS_DIR / "X_train.csv"
DATA_SPLITS_X_TEST_PATH = ARTIFACT_DATA_SPLITS_DIR / "X_test.csv"
DATA_SPLITS_Y_TRAIN_PATH = ARTIFACT_DATA_SPLITS_DIR / "y_train.csv"
DATA_SPLITS_Y_TEST_PATH = ARTIFACT_DATA_SPLITS_DIR / "y_test.csv"

ARTIFACT_BINNING_PREBIN_DIR = ARTIFACT_BINNING_DIR / "prebin"
ARTIFACT_BINNING_PREBIN_DIR.mkdir(parents=True,exist_ok=True)

PREBIN_SELECTED_X_TRAIN_PATH = ARTIFACT_BINNING_PREBIN_DIR / "X_train_selected_woe.csv"
PREBIN_SELECTED_X_TEST_PATH = ARTIFACT_BINNING_PREBIN_DIR / "X_test_selected_woe.csv"
PREBIN_IV_DF_PATH = ARTIFACT_BINNING_PREBIN_DIR / "iv_df.csv"
PREBIN_CAT_BIN_DF_PATH = ARTIFACT_BINNING_PREBIN_DIR / "cat_bin_df.csv"
PREBIN_NUMERICAL_FEATURE_BINS_PATHS = ARTIFACT_BINNING_PREBIN_DIR / "numerical_feature_bins.pkl"
PREBIN_SELECTED_FEATURES_PATHS = ARTIFACT_BINNING_PREBIN_DIR / "selected_features.json"

# FEATURE BIN MERGING 
ARTIFACT_BINNING_POSTBIN_MANUAL_DIR = ARTIFACT_BINNING_DIR / 'postbin_manual'
ARTIFACT_BINNING_POSTBIN_MANUAL_DIR.mkdir(parents=True,exist_ok=True)

ARTIFACT_POSTBIN_SELECTED_FEATURES_PATH = ARTIFACT_BINNING_POSTBIN_MANUAL_DIR / 'selected_features.json'
ARTIFACT_POSTBIN_SELECTED_NUM_BINS_PATH = ARTIFACT_BINNING_POSTBIN_MANUAL_DIR / 'selected_num_bins.pkl'

ARTIFACT_DATA_FINAL_DIR = ARTIFACT_DATA_DIR / 'final'
ARTIFACT_DATA_FINAL_DIR.mkdir(parents=True,exist_ok=True)

DATA_FINAL_X_TRAIN_PATH = ARTIFACT_DATA_FINAL_DIR / 'X_train_final.csv'
DATA_FINAL_X_TEST_PATH = ARTIFACT_DATA_FINAL_DIR / 'X_test_final.csv'

FINAL_SELECTED_FEATURES_PATH = ARTIFACT_DATA_FINAL_DIR / 'selected_features.json'
FINAL_SELECTED_NUM_BINS_PATH = ARTIFACT_DATA_FINAL_DIR / 'selected_num_bins.pkl'

FINAL_MODEL_FEATURES = ARTIFACT_DATA_FINAL_DIR / 'model_features.json'



# MODEL TRAINING
ARTIFACT_MODEL_PATH = ARTIFACT_MODEL_DIR / 'model.pkl'
MODEL_FEATURE_IMPORTANCE_PATH = ARTIFACT_MODEL_DIR / "feature_importance.csv"

# MODEL EVALUTION
MODEL_EVAL_METRICS_PATH = ARTIFACT_MODEL_EVAL_DIR / 'metrics.json'
MODEL_EVAL_ROC_CURVE_PATH  = ARTIFACT_MODEL_EVAL_DIR / 'roc_curve.png'
MODEL_EVAL_CALLIBRATION_PLOT_PATH= ARTIFACT_MODEL_EVAL_DIR / "calibration_plot.png"

# SCORECARD 
FINAL_SCORECARD_RULES_PATH = ARTIFACT_SCORECARD_DIR / 'final_scorecard_rules.csv'
SCORECARD_SCALING_PARAMS_PATH = ARTIFACT_SCORECARD_DIR / 'scorecard_scaling_params.json'

FINAL_SCORECARD_TRAIN_PATH = ARTIFACT_SCORECARD_DIR / 'scored_train.csv'
FINAL_SCORECARD_PERFORMANCE_TABLE_PATH = ARTIFACT_SCORECARD_DIR / 'scorecard_table.csv'

SCORECARD_METRICS_PATH = ARTIFACT_SCORECARD_DIR / 'metrics.json'

SCORECARD_CATEGORICAL_RULES = ARTIFACT_SCORECARD_DIR / 'categorical_rules.csv'
SCORECARD_NUMERICAL_RULES = ARTIFACT_SCORECARD_DIR / 'numerical_rules.csv'


SCORECARD_CATEGORICAL_LOOKUP = ARTIFACT_SCORECARD_DIR / 'categorical_lookup.pkl'
SCORECARD_NUMERICAL_LOOKUP = ARTIFACT_SCORECARD_DIR / 'numerical_lookup.pkl'





SPECIAL_CODES = {
    "SC_-99999": [-99999],
    "SC_-88888": [-88888],
    "SC_-77777": [-77777],
    "SC_-66666": [-66666],
}
