columns:
  - SK_ID_CURR: int64
  - SK_ID_BUREAU: int64
  - CREDIT_ACTIVE: object
  - CREDIT_CURRENCY: object
  - DAYS_CREDIT: int64
  - CREDIT_DAY_OVERDUE: int64
  - DAYS_CREDIT_ENDDATE: float64
  - DAYS_ENDDATE_FACT: float64
  - AMT_CREDIT_MAX_OVERDUE: float64
  - CNT_CREDIT_PROLONG: int64
  - AMT_CREDIT_SUM: float64
  - AMT_CREDIT_SUM_DEBT: float64
  - AMT_CREDIT_SUM_LIMIT: float64
  - AMT_CREDIT_SUM_OVERDUE: float64
  - CREDIT_TYPE: object
  - DAYS_CREDIT_UPDATE: int64
  - AMT_ANNUITY: float64

categorical_columns:
  - CREDIT_ACTIVE
  - CREDIT_CURRENCY
  - CREDIT_TYPE

numerical_columns:
  - SK_ID_CURR
  - SK_ID_BUREAU
  - DAYS_CREDIT
  - CREDIT_DAY_OVERDUE
  - DAYS_CREDIT_ENDDATE
  - DAYS_ENDDATE_FACT
  - AMT_CREDIT_MAX_OVERDUE
  - CNT_CREDIT_PROLONG
  - AMT_CREDIT_SUM
  - AMT_CREDIT_SUM_DEBT
  - AMT_CREDIT_SUM_LIMIT
  - AMT_CREDIT_SUM_OVERDUE
  - DAYS_CREDIT_UPDATE
  - AMT_ANNUITY