columns:
  - SK_ID_PREV: int64
  - SK_ID_CURR: int64
  - MONTHS_BALANCE: int64
  - AMT_BALANCE: float64
  - AMT_CREDIT_LIMIT_ACTUAL: int64
  - AMT_DRAWINGS_ATM_CURRENT: float64
  - AMT_DRAWINGS_CURRENT: float64
  - AMT_DRAWINGS_OTHER_CURRENT: float64
  - AMT_DRAWINGS_POS_CURRENT: float64
  - AMT_INST_MIN_REGULARITY: float64
  - AMT_PAYMENT_CURRENT: float64
  - AMT_PAYMENT_TOTAL_CURRENT: float64
  - AMT_RECEIVABLE_PRINCIPAL: float64
  - AMT_RECIVABLE: float64
  - AMT_TOTAL_RECEIVABLE: float64
  - CNT_DRAWINGS_ATM_CURRENT: float64
  - CNT_DRAWINGS_CURRENT: int64
  - CNT_DRAWINGS_OTHER_CURRENT: float64
  - CNT_DRAWINGS_POS_CURRENT: float64
  - CNT_INSTALMENT_MATURE_CUM: float64
  - NAME_CONTRACT_STATUS: object
  - SK_DPD: int64
  - SK_DPD_DEF: int64

categorical_columns:
  - NAME_CONTRACT_STATUS

numerical_columns:
  - SK_ID_PREV
  - SK_ID_CURR
  - MONTHS_BALANCE
  - AMT_BALANCE
  - AMT_CREDIT_LIMIT_ACTUAL
  - AMT_DRAWINGS_ATM_CURRENT
  - AMT_DRAWINGS_CURRENT
  - AMT_DRAWINGS_OTHER_CURRENT
  - AMT_DRAWINGS_POS_CURRENT
  - AMT_INST_MIN_REGULARITY
  - AMT_PAYMENT_CURRENT
  - AMT_PAYMENT_TOTAL_CURRENT
  - AMT_RECEIVABLE_PRINCIPAL
  - AMT_RECIVABLE
  - AMT_TOTAL_RECEIVABLE
  - CNT_DRAWINGS_ATM_CURRENT
  - CNT_DRAWINGS_CURRENT
  - CNT_DRAWINGS_OTHER_CURRENT
  - CNT_DRAWINGS_POS_CURRENT
  - CNT_INSTALMENT_MATURE_CUM
  - SK_DPD
  - SK_DPD_DEF