columns:
  - SK_ID_PREV: int64
  - SK_ID_CURR: int64
  - NAME_CONTRACT_TYPE: object
  - AMT_ANNUITY: float64
  - AMT_APPLICATION: float64
  - AMT_CREDIT: float64
  - AMT_DOWN_PAYMENT: float64
  - AMT_GOODS_PRICE: float64
  - WEEKDAY_APPR_PROCESS_START: object
  - HOUR_APPR_PROCESS_START: int64
  - FLAG_LAST_APPL_PER_CONTRACT: object
  - NFLAG_LAST_APPL_IN_DAY: int64
  - RATE_DOWN_PAYMENT: float64
  - RATE_INTEREST_PRIMARY: float64
  - RATE_INTEREST_PRIVILEGED: float64
  - NAME_CASH_LOAN_PURPOSE: object
  - NAME_CONTRACT_STATUS: object
  - DAYS_DECISION: int64
  - NAME_PAYMENT_TYPE: object
  - CODE_REJECT_REASON: object
  - NAME_TYPE_SUITE: object
  - NAME_CLIENT_TYPE: object
  - NAME_GOODS_CATEGORY: object
  - NAME_PORTFOLIO: object
  - NAME_PRODUCT_TYPE: object
  - CHANNEL_TYPE: object
  - SELLERPLACE_AREA: int64
  - NAME_SELLER_INDUSTRY: object
  - CNT_PAYMENT: float64
  - NAME_YIELD_GROUP: object
  - PRODUCT_COMBINATION: object
  - DAYS_FIRST_DRAWING: float64
  - DAYS_FIRST_DUE: float64
  - DAYS_LAST_DUE_1ST_VERSION: float64
  - DAYS_LAST_DUE: float64
  - DAYS_TERMINATION: float64
  - NFLAG_INSURED_ON_APPROVAL: float64

categorical_columns:
  - NAME_CONTRACT_TYPE
  - WEEKDAY_APPR_PROCESS_START
  - FLAG_LAST_APPL_PER_CONTRACT
  - NAME_CASH_LOAN_PURPOSE
  - NAME_CONTRACT_STATUS
  - NAME_PAYMENT_TYPE
  - CODE_REJECT_REASON
  - NAME_TYPE_SUITE
  - NAME_CLIENT_TYPE
  - NAME_GOODS_CATEGORY
  - NAME_PORTFOLIO
  - NAME_PRODUCT_TYPE
  - CHANNEL_TYPE
  - NAME_SELLER_INDUSTRY
  - NAME_YIELD_GROUP
  - PRODUCT_COMBINATION

numerical_columns:
  - SK_ID_PREV
  - SK_ID_CURR
  - AMT_ANNUITY
  - AMT_APPLICATION
  - AMT_CREDIT
  - AMT_DOWN_PAYMENT
  - AMT_GOODS_PRICE
  - HOUR_APPR_PROCESS_START
  - NFLAG_LAST_APPL_IN_DAY
  - RATE_DOWN_PAYMENT
  - RATE_INTEREST_PRIMARY
  - RATE_INTEREST_PRIVILEGED
  - DAYS_DECISION
  - SELLERPLACE_AREA
  - CNT_PAYMENT
  - DAYS_FIRST_DRAWING
  - DAYS_FIRST_DUE
  - DAYS_LAST_DUE_1ST_VERSION
  - DAYS_LAST_DUE
  - DAYS_TERMINATION
  - NFLAG_INSURED_ON_APPROVAL